# Hadolint Configuration
# See https://github.com/hadolint/hadolint for configuration options

# Fail on errors
failure-threshold: error

# Correct list format for hadolint
ignored:
  - DL3008 # Pin versions in apt-get install
  - DL3018 # Pin versions in apk add (if using alpine)
  - DL3006 # Always use a specific tag for base images
  - SC2086 # Double quotes around variable expansions

override:
  warning:
    - DL3006 # Always use a specific tag for base images

# Specific rule configurations
strict-labels: false

